# Generated by Django 2.2.6 on 2019-12-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0002_auto_20191101_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(default='', max_length=250)),
                ('correct', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usrs',
            name='usr',
            field=models.CharField(default='', max_length=250),
        ),
    ]
